// site-front/pages/forgot-password.vue
<template>
  <div class="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-md w-full space-y-8">
      <div>
        <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">
          Reset your password
        </h2>
        <p class="mt-2 text-center text-sm text-gray-600">
          Enter your email address and we'll send you a password reset link.
        </p>
      </div>
      <form class="mt-8 space-y-6" @submit.prevent="handleForgotPassword">
        <div>
          <label for="email" class="sr-only">Email address</label>
          <input
            id="email"
            v-model="form.email"
            name="email"
            type="email"
            autocomplete="email"
            required
            class="appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
            placeholder="Email address"
          />
        </div>

        <div v-if="success" class="text-sm text-green-600 text-center">
          {{ success }}
        </div>
        <div v-if="error" class="text-sm text-red-600 text-center">
          {{ error }}
        </div>

        <div>
          <button
            type="submit"
            :disabled="loading"
            class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:opacity-50"
          >
            <span v-if="loading">Sending...</span>
            <span v-else>Send reset link</span>
          </button>
        </div>

        <div class="text-center">
          <NuxtLink to="/login" class="text-sm font-medium text-indigo-600 hover:text-indigo-500">
            Back to login
          </NuxtLink>
        </div>
      </form>
    </div>
  </div>
</template>

<script setup lang="ts">
definePageMeta({
  layout: false,
  middleware: 'auth'
})

const api = useApi()
const { toastSuccess, toastError } = useAlerts()

const form = ref({
  email: '',
})

const loading = ref(false)
const error = ref('')
const success = ref('')

async function handleForgotPassword() {
  loading.value = true
  error.value = ''
  success.value = ''

  try {
    const response = await api.post('/auth/forgot-password', form.value)
    success.value = response.message || 'If the email exists, a password reset link has been sent.'
    toastSuccess(success.value)
  } catch (err: any) {
    error.value = err.message || 'Failed to send reset link. Please try again.'
    toastError(error.value)
  } finally {
    loading.value = false
  }
}
</script>

// site-front/src/routes/forgot-password/index.tsx
import { $, component$, useSignal } from "@builder.io/qwik";
import { Link } from "@builder.io/qwik-city";
import type { DocumentHead } from "@builder.io/qwik-city";
import { apiPost } from "~/lib/api";
import { ErrorState } from "~/components/site-chrome/site-chrome";

export default component$(() => {
  const email = useSignal("");
  const loading = useSignal(false);
  const error = useSignal("");
  const success = useSignal("");

  const handleSubmit = $(async () => {
    loading.value = true;
    error.value = "";
    success.value = "";
    try {
      await apiPost("/auth/forgot-password", { email: email.value }, false);
      success.value = "If an account exists for that email, a reset link has been sent.";
      alert(success.value);
    } catch (err) {
      error.value = err instanceof Error ? err.message : "Unable to send reset email.";
    } finally {
      loading.value = false;
    }
  });

  return (
    <div class="auth-shell">
      <div class="auth-card card">
        <div class="card-body">
          <h1 style={{ textAlign: "center", marginTop: 0 }}>Forgot password</h1>
          <p style={{ textAlign: "center", color: "var(--color-muted)" }}>
            Enter your email and we will send reset instructions.
          </p>

          <form preventdefault:submit onSubmit$={handleSubmit} style={{ marginTop: "1.5rem" }}>
            <div class="form-group">
              <label for="email">Email</label>
              <input
                id="email"
                class="form-control"
                type="email"
                required
                value={email.value}
                onInput$={(event) => {
                  email.value = (event.target as HTMLInputElement).value;
                }}
              />
            </div>
            {error.value ? <ErrorState message={error.value} /> : null}
            {success.value ? <div class="alert alert-success">{success.value}</div> : null}
            <button type="submit" class="btn btn-primary" style={{ width: "100%" }} disabled={loading.value}>
              {loading.value ? "Sending…" : "Send reset link"}
            </button>
          </form>

          <p style={{ textAlign: "center", marginTop: "1rem" }}>
            <Link href="/login">Back to login</Link>
          </p>
        </div>
      </div>
    </div>
  );
});

export const head: DocumentHead = {
  title: "Forgot password — ULSP",
};
