// site-front/pages/register.vue
<template>
  <div class="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-md w-full space-y-8">
      <div>
        <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">
          Create your account
        </h2>
        <p class="mt-2 text-center text-sm text-gray-600">
          Already have an account?
          <NuxtLink to="/login" class="font-medium text-indigo-600 hover:text-indigo-500">
            Sign in
          </NuxtLink>
        </p>
      </div>
      <form class="mt-8 space-y-6" @submit.prevent="handleRegister">
        <div class="space-y-4">
          <div>
            <label for="email" class="block text-sm font-medium text-gray-700">Email *</label>
            <input
              id="email"
              v-model="form.email"
              name="email"
              type="email"
              autocomplete="email"
              required
              class="mt-1 appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
              placeholder="your@email.com"
            />
          </div>
          <div class="grid grid-cols-2 gap-4">
            <div>
              <label for="first_name" class="block text-sm font-medium text-gray-700">First Name</label>
              <input
                id="first_name"
                v-model="form.first_name"
                name="first_name"
                type="text"
                class="mt-1 appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
              />
            </div>
            <div>
              <label for="last_name" class="block text-sm font-medium text-gray-700">Last Name</label>
              <input
                id="last_name"
                v-model="form.last_name"
                name="last_name"
                type="text"
                class="mt-1 appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
              />
            </div>
          </div>
          <div>
            <label for="company" class="block text-sm font-medium text-gray-700">Company</label>
            <input
              id="company"
              v-model="form.company"
              name="company"
              type="text"
              class="mt-1 appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
            />
          </div>
          <div>
            <label for="phone" class="block text-sm font-medium text-gray-700">Phone</label>
            <input
              id="phone"
              v-model="form.phone"
              name="phone"
              type="tel"
              class="mt-1 appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
            />
          </div>
          <div>
            <label for="password" class="block text-sm font-medium text-gray-700">Password *</label>
            <input
              id="password"
              v-model="form.password"
              name="password"
              type="password"
              autocomplete="new-password"
              required
              minlength="8"
              class="mt-1 appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
              placeholder="Minimum 8 characters"
            />
          </div>
          <div>
            <label for="password_confirmation" class="block text-sm font-medium text-gray-700">Confirm Password *</label>
            <input
              id="password_confirmation"
              v-model="form.password_confirmation"
              name="password_confirmation"
              type="password"
              autocomplete="new-password"
              required
              class="mt-1 appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
            />
          </div>
        </div>

        <div v-if="error" class="text-sm text-red-600 text-center">
          {{ error }}
        </div>

        <div>
          <button
            type="submit"
            :disabled="loading"
            class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:opacity-50"
          >
            <span v-if="loading">Creating account...</span>
            <span v-else>Create account</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>

<script setup lang="ts">
definePageMeta({
  layout: false,
  middleware: 'auth'
})

const authStore = useAuthStore()
const api = useApi()
const { toastSuccess, toastError } = useAlerts()

const form = ref({
  email: '',
  first_name: '',
  last_name: '',
  company: '',
  phone: '',
  password: '',
  password_confirmation: '',
})

const loading = ref(false)
const error = ref('')

async function handleRegister() {
  if (form.value.password !== form.value.password_confirmation) {
    error.value = 'Passwords do not match'
    return
  }

  loading.value = true
  error.value = ''

  try {
    const response = await api.post<{
      customer: any
      token: string
      token_type: string
    }>('/auth/register', form.value)

    authStore.setAuth(response.customer, response.token)
    toastSuccess('Account created successfully')
    await navigateTo('/')
  } catch (err: any) {
    if (err.message) {
      error.value = err.message
    } else if (err.response?.data?.errors) {
      const errors = err.response.data.errors
      error.value = Object.values(errors).flat().join(', ')
    } else {
      error.value = 'Failed to create account. Please try again.'
    }
    toastError(error.value)
  } finally {
    loading.value = false
  }
}
</script>

// site-front/src/routes/register/index.tsx
import { $, component$, useSignal } from "@builder.io/qwik";
import { Link, useNavigate } from "@builder.io/qwik-city";
import type { DocumentHead } from "@builder.io/qwik-city";
import { apiPost } from "~/lib/api";
import { setAuth } from "~/lib/auth";
import type { AuthLoginResponse } from "~/lib/types";
import { ErrorState } from "~/components/site-chrome/site-chrome";

export default component$(() => {
  const nav = useNavigate();
  const email = useSignal("");
  const firstName = useSignal("");
  const lastName = useSignal("");
  const password = useSignal("");
  const loading = useSignal(false);
  const error = useSignal("");

  const handleSubmit = $(async () => {
    loading.value = true;
    error.value = "";
    try {
      const response = await apiPost<AuthLoginResponse>(
        "/auth/register",
        {
          email: email.value,
          password: password.value,
          first_name: firstName.value,
          last_name: lastName.value,
        },
        false,
      );
      setAuth(response.token, response.customer);
      alert("Account created successfully.");
      await nav("/app");
    } catch (err) {
      error.value = err instanceof Error ? err.message : "Registration failed.";
    } finally {
      loading.value = false;
    }
  });

  return (
    <div class="auth-shell">
      <div class="auth-card card">
        <div class="card-body">
          <h1 style={{ textAlign: "center", marginTop: 0 }}>Create account</h1>
          <p style={{ textAlign: "center", color: "var(--color-muted)" }}>
            Already have an account? <Link href="/login">Sign in</Link>
          </p>

          <form preventdefault:submit onSubmit$={handleSubmit} style={{ marginTop: "1.5rem" }}>
            <div class="form-group">
              <label for="email">Email</label>
              <input
                id="email"
                class="form-control"
                type="email"
                required
                value={email.value}
                onInput$={(event) => {
                  email.value = (event.target as HTMLInputElement).value;
                }}
              />
            </div>
            <div class="grid grid-2">
              <div class="form-group">
                <label for="first_name">First name</label>
                <input
                  id="first_name"
                  class="form-control"
                  value={firstName.value}
                  onInput$={(event) => {
                    firstName.value = (event.target as HTMLInputElement).value;
                  }}
                />
              </div>
              <div class="form-group">
                <label for="last_name">Last name</label>
                <input
                  id="last_name"
                  class="form-control"
                  value={lastName.value}
                  onInput$={(event) => {
                    lastName.value = (event.target as HTMLInputElement).value;
                  }}
                />
              </div>
            </div>
            <div class="form-group">
              <label for="password">Password</label>
              <input
                id="password"
                class="form-control"
                type="password"
                minLength={8}
                required
                value={password.value}
                onInput$={(event) => {
                  password.value = (event.target as HTMLInputElement).value;
                }}
              />
            </div>
            {error.value ? <ErrorState message={error.value} /> : null}
            <button type="submit" class="btn btn-primary" style={{ width: "100%" }} disabled={loading.value}>
              {loading.value ? "Creating account…" : "Create account"}
            </button>
          </form>
        </div>
      </div>
    </div>
  );
});

export const head: DocumentHead = {
  title: "Register — ULSP",
};
