// site-front/src/routes/app/profile/index.tsx
import { $, component$, useSignal, useVisibleTask$ } from "@builder.io/qwik";
import type { DocumentHead } from "@builder.io/qwik-city";
import { apiGet, apiPut, unwrapData } from "~/lib/api";
import { getCustomer, getToken, setAuth } from "~/lib/auth";
import { ErrorState, LoadingState } from "~/components/site-chrome/site-chrome";
import type { Customer } from "~/lib/types";

export default component$(() => {
  const loading = useSignal(true);
  const saving = useSignal(false);
  const error = useSignal("");

  const email = useSignal("");
  const firstName = useSignal("");
  const lastName = useSignal("");
  const company = useSignal("");
  const phone = useSignal("");
  const password = useSignal("");
  const passwordConfirmation = useSignal("");

  const applyCustomer = $((customer: Customer) => {
    email.value = customer.email || "";
    firstName.value = customer.first_name || "";
    lastName.value = customer.last_name || "";
    company.value = customer.company || "";
    phone.value = customer.phone || "";
  });

  useVisibleTask$(async () => {
    loading.value = true;
    error.value = "";
    try {
      const response = await apiGet<Customer | { data: Customer }>("/customer/me");
      await applyCustomer(unwrapData(response));
    } catch (err) {
      const stored = getCustomer();
      if (stored) {
        await applyCustomer(stored);
      } else {
        error.value = err instanceof Error ? err.message : "Failed to load profile.";
      }
    } finally {
      loading.value = false;
    }
  });

  const handleSubmit = $(async () => {
    if (password.value && password.value !== passwordConfirmation.value) {
      error.value = "Passwords do not match.";
      return;
    }

    saving.value = true;
    error.value = "";
    try {
      const payload: Record<string, string> = {
        email: email.value,
        first_name: firstName.value,
        last_name: lastName.value,
        company: company.value,
        phone: phone.value,
      };
      if (password.value) {
        payload.password = password.value;
        payload.password_confirmation = passwordConfirmation.value;
      }

      const response = await apiPut<Customer | { data: Customer }>("/customer/profile", payload);
      const updated = unwrapData(response);
      const token = getToken();
      if (token) {
        setAuth(token, updated);
      }
      password.value = "";
      passwordConfirmation.value = "";
      alert("Profile updated successfully.");
    } catch (err) {
      error.value = err instanceof Error ? err.message : "Failed to update profile.";
    } finally {
      saving.value = false;
    }
  });

  return (
    <>
      <div class="page-header">
        <h1>Profile</h1>
        <p>Manage your account information.</p>
      </div>

      {loading.value ? (
        <LoadingState />
      ) : (
        <section class="card">
          <div class="card-body">
            <form preventdefault:submit onSubmit$={handleSubmit}>
              <div class="grid grid-2">
                <div class="form-group">
                  <label for="email">Email</label>
                  <input
                    id="email"
                    class="form-control"
                    type="email"
                    required
                    value={email.value}
                    onInput$={(event) => {
                      email.value = (event.target as HTMLInputElement).value;
                    }}
                  />
                </div>
                <div class="form-group">
                  <label for="phone">Phone</label>
                  <input
                    id="phone"
                    class="form-control"
                    value={phone.value}
                    onInput$={(event) => {
                      phone.value = (event.target as HTMLInputElement).value;
                    }}
                  />
                </div>
                <div class="form-group">
                  <label for="first_name">First name</label>
                  <input
                    id="first_name"
                    class="form-control"
                    value={firstName.value}
                    onInput$={(event) => {
                      firstName.value = (event.target as HTMLInputElement).value;
                    }}
                  />
                </div>
                <div class="form-group">
                  <label for="last_name">Last name</label>
                  <input
                    id="last_name"
                    class="form-control"
                    value={lastName.value}
                    onInput$={(event) => {
                      lastName.value = (event.target as HTMLInputElement).value;
                    }}
                  />
                </div>
                <div class="form-group" style={{ gridColumn: "1 / -1" }}>
                  <label for="company">Company</label>
                  <input
                    id="company"
                    class="form-control"
                    value={company.value}
                    onInput$={(event) => {
                      company.value = (event.target as HTMLInputElement).value;
                    }}
                  />
                </div>
              </div>

              <h2 style={{ marginTop: "1.5rem" }}>Change password</h2>
              <div class="grid grid-2">
                <div class="form-group">
                  <label for="password">New password</label>
                  <input
                    id="password"
                    class="form-control"
                    type="password"
                    minLength={8}
                    value={password.value}
                    onInput$={(event) => {
                      password.value = (event.target as HTMLInputElement).value;
                    }}
                  />
                </div>
                <div class="form-group">
                  <label for="password_confirmation">Confirm password</label>
                  <input
                    id="password_confirmation"
                    class="form-control"
                    type="password"
                    value={passwordConfirmation.value}
                    onInput$={(event) => {
                      passwordConfirmation.value = (event.target as HTMLInputElement).value;
                    }}
                  />
                </div>
              </div>

              {error.value ? <ErrorState message={error.value} /> : null}

              <div style={{ display: "flex", justifyContent: "flex-end", gap: "0.5rem", marginTop: "1rem" }}>
                <button type="submit" class="btn btn-primary" disabled={saving.value}>
                  {saving.value ? "Saving…" : "Save changes"}
                </button>
              </div>
            </form>
          </div>
        </section>
      )}
    </>
  );
});

export const head: DocumentHead = {
  title: "Profile — ULSP",
};

// site-front/pages/profile.vue
<template>
  <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
    <div class="mb-8">
      <h1 class="text-3xl font-bold text-gray-900">Profile Settings</h1>
      <p class="mt-2 text-sm text-gray-600">Manage your account information</p>
    </div>

    <div v-if="loading" class="text-center py-12">
      <div class="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-indigo-600"></div>
    </div>

    <div v-else class="bg-white shadow rounded-lg overflow-hidden">
      <form @submit.prevent="handleUpdateProfile" class="px-6 py-5 space-y-6">
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Email *</label>
            <input
              v-model="form.email"
              type="email"
              required
              class="w-full px-3 py-2 border rounded-md"
            />
          </div>
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Phone</label>
            <input
              v-model="form.phone"
              type="tel"
              class="w-full px-3 py-2 border rounded-md"
            />
          </div>
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">First Name</label>
            <input
              v-model="form.first_name"
              type="text"
              class="w-full px-3 py-2 border rounded-md"
            />
          </div>
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Last Name</label>
            <input
              v-model="form.last_name"
              type="text"
              class="w-full px-3 py-2 border rounded-md"
            />
          </div>
          <div class="md:col-span-2">
            <label class="block text-sm font-medium text-gray-700 mb-1">Company</label>
            <input
              v-model="form.company"
              type="text"
              class="w-full px-3 py-2 border rounded-md"
            />
          </div>
        </div>

        <div class="border-t border-gray-200 pt-6">
          <h3 class="text-lg font-medium text-gray-900 mb-4">Change Password</h3>
          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1">New Password</label>
              <input
                v-model="form.password"
                type="password"
                minlength="8"
                class="w-full px-3 py-2 border rounded-md"
                placeholder="Leave blank to keep current"
              />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1">Confirm Password</label>
              <input
                v-model="form.password_confirmation"
                type="password"
                class="w-full px-3 py-2 border rounded-md"
                placeholder="Confirm new password"
              />
            </div>
          </div>
        </div>

        <div v-if="error" class="text-sm text-red-600">
          {{ error }}
        </div>

        <div class="flex justify-end gap-2 pt-4 border-t border-gray-200">
          <button
            type="button"
            @click="resetForm"
            class="px-4 py-2 bg-gray-200 text-gray-800 rounded-md hover:bg-gray-300"
          >
            Reset
          </button>
          <button
            type="submit"
            :disabled="saving"
            class="px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700 disabled:opacity-50"
          >
            <span v-if="saving">Saving...</span>
            <span v-else>Save Changes</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>

<script setup lang="ts">
definePageMeta({
  middleware: 'auth'
})

const authStore = useAuthStore()
const api = useApi()
const { CUSTOMER_API_BASE_URL } = api
const { toastSuccess, toastError } = useAlerts()

const loading = ref(true)
const saving = ref(false)
const error = ref('')

const form = ref({
  email: '',
  first_name: '',
  last_name: '',
  company: '',
  phone: '',
  password: '',
  password_confirmation: '',
})

onMounted(async () => {
  await fetchProfile()
})

async function fetchProfile() {
  loading.value = true
  try {
    const response = await api.get(`${CUSTOMER_API_BASE_URL}/me`)
    const customer = response.data || response
    form.value = {
      email: customer.email || '',
      first_name: customer.first_name || '',
      last_name: customer.last_name || '',
      company: customer.company || '',
      phone: customer.phone || '',
      password: '',
      password_confirmation: '',
    }
  } catch (error) {
    console.error('Failed to fetch profile:', error)
    toastError('Failed to load profile')
  } finally {
    loading.value = false
  }
}

function resetForm() {
  fetchProfile()
}

async function handleUpdateProfile() {
  if (form.value.password && form.value.password !== form.value.password_confirmation) {
    error.value = 'Passwords do not match'
    return
  }

  saving.value = true
  error.value = ''

  try {
    const payload: any = {
      email: form.value.email,
      first_name: form.value.first_name,
      last_name: form.value.last_name,
      company: form.value.company,
      phone: form.value.phone,
    }

    if (form.value.password) {
      payload.password = form.value.password
      payload.password_confirmation = form.value.password_confirmation
    }

    const response = await api.put(`${CUSTOMER_API_BASE_URL}/profile`, payload)
    const updated = response.data || response
    
    // Update auth store with new customer data
    authStore.setAuth(updated, authStore.token!)
    
    toastSuccess('Profile updated successfully')
    form.value.password = ''
    form.value.password_confirmation = ''
  } catch (err: any) {
    if (err.message) {
      error.value = err.message
    } else if (err.response?.data?.errors) {
      const errors = err.response.data.errors
      error.value = Object.values(errors).flat().join(', ')
    } else {
      error.value = 'Failed to update profile. Please try again.'
    }
    toastError(error.value)
  } finally {
    saving.value = false
  }
}
</script>
